### ISSUE TITLE
ImportError: No module named pytz

### ISSUE THREAD

**Issue by timokau** [tbabej/task.default-date-time#1]
Hi
I installed the hook following the Readme's instructions, but every time I want try it throws the error "ImportError: No module named pytz".
I tried installing pytz with pip3, but it already was installed.

**Comment by tbabej** [comment]
Hello,

you're absolutely correct, the code uses tasklib version which has not yet been merged. Install tasklib using following command:

```
sudo pip install --force git+git://github.com/tbabej/tasklib@localized_timestamps
```

It will also install the dependencies, the pytz (Python timezones) library.

**Comment by tbabej** [comment]
Note: Since it seems you already have python3 version of the pytz library, it must be the case that hooks are getting executed with python2 interpreter (where you don't have the pytz library). To run the hooks with python3, you will have to edit the first line (shebang) to the location of your python3 executable. Most likely it will be:

```
#!/usr/bin/python3
```

In any case, you will need to update the tasklib library, either with pip or pip3 using the command above and then make sure the hook uses the same python interpreter version.

**Comment by timokau** [comment]
I now installed pytz with pip & pip3, both with and without sudo (although I don't think that's the cleanest possible solution)
In addition I installed the updated tasklib.
Now it works. The only error is, that task apparently has no attribute called "touched" (maybe the update of tasklib hasn't worked correctly), but I just removed the confirmation that the date has been updated, since I don't really need that anyway.
Thank you!

**Comment by tbabej** [comment]
You're right, indeed, I have some uncommited changes in the repo. I'll try to fix it when I find a minute.

**Comment by timokau** [comment]
Thanks this solves one of the thinks that were bugging me with taskwarrior.
I just discovered another problem though: When I try to clear out a due date with "mod xyz due: " the hook runs and the due date ends up being "1970-01-01 01:00:00" (the hook is configured to set it to 20:30).

**Comment by tbabej** [comment]
This is a bug in the taskwarrior, to fix it, you need to build and install current development branch, 2.4.1. (or wait until it's released)

**Comment by timokau** [comment]
Okay  It's not that important, that was the first time I needed to do that. I just wanted to let you know.
Thanks for the quick help.
